ALTER TABLE funcionario
ADD COLUMN data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
COMMENT 'DATA QUE O FUNCIONARIO FOI INSCRITO';
alter table FUNCIONARIO add column CADASTRO_ATUALIZADO TIMESTAMP COMMENT 'DATA QUE O FUNCIONARIO ATUALIZADO';