ALTER TABLE FUNCIONARIO ADD COLUMN CEP varchar(50);
ALTER TABLE FUNCIONARIO ADD COLUMN RUA VARCHAR(100);
ALTER TABLE FUNCIONARIO ADD COLUMN BAIRRO VARCHAR(100);
ALTER TABLE FUNCIONARIO ADD COLUMN CIDADE VARCHAR(100);
ALTER TABLE FUNCIONARIO ADD COLUMN ESTADO VARCHAR (10);